import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Text Translator",
  description: "Generated by Khalif RTG for HNG",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>

        <meta httpEquiv="origin-trial" content="ApCBF9l/iPZDKYDSJn+jnE/D+8wJv3SI7BMadokh+J1EN8Fg/5mNHOkrj9UUcXL32oytnV6OCAQvKKCsVDGolwEAAAB1eyJvcmlnaW4iOiJjaHJvbWUtZXh0ZW5zaW9uOi8vZ2xjaW1lcG5sam9ob2xkbWpjaGtsb2Fma2dnZm9pamgiLCJmZWF0dXJlIjoiTGFuZ3VhZ2VEZXRlY3Rpb25BUEkiLCJleHBpcnkiOjE3NDk1OTk5OTl9"/>

        <meta httpEquiv="origin-trial" content="Ar9az7JeZuwcW0lxCfgIHTdNZQCAb6HFCHM4LV7MaGuNZzLz1/e4Bbl4kwnrvSuERBsqtsp0spj2Xuyx2OdH4gEAAABveyJvcmlnaW4iOiJjaHJvbWUtZXh0ZW5zaW9uOi8vZ2xjaW1lcG5sam9ob2xkbWpjaGtsb2Fma2dnZm9pamgiLCJmZWF0dXJlIjoiVHJhbnNsYXRpb25BUEkiLCJleHBpcnkiOjE3NTMxNDI0MDB9"/>

        <meta httpEquiv="origin-trial" content="AuPX7td3Ekz0LHrz5AD3DiZmxB7Z2FZfAPbi+pNvlLdK8YjXniMnFX7yhb2DOA3qFg62RiX12UjcaOffOBwYfgwAAABzeyJvcmlnaW4iOiJjaHJvbWUtZXh0ZW5zaW9uOi8vZ2xjaW1lcG5sam9ob2xkbWpjaGtsb2Fma2dnZm9pamgiLCJmZWF0dXJlIjoiQUlTdW1tYXJpemF0aW9uQVBJIiwiZXhwaXJ5IjoxNzUzMTQyNDAwfQ=="/>

        <link href="https://fonts.googleapis.com/css2?family=Sigmar&display=swap" rel="stylesheet"/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
